### ISSUE TITLE
Avoid passing `dict` to `__init__` methods

### ISSUE THREAD

**Issue by Hans-Smit** [ThomasAlbin/SolarY#12]
In the `camera.py` module, the `CCD` class is defined as this,

```
class CCD:

    def __init__(self, ccd_config: t.Dict[str, t.Any]):
        # Set the attributes dynamically in a for loop and set the values accordingly.
        valid_keys = ['pixels', 'pixel_size', 'dark_noise', 'readout_noise', 'full_well',
                      'quantum_eff']
        for key in valid_keys:
            setattr(self, key, ccd_config.get(key))
```

This is very convenient for the developer, but it fails with respect to type checking, API signature visibility, and removes code completion from many IDE's. 

Proposed code,

```
class CCD:

    def __init__(self,
                 pixels: float,
                 pixel_size: t.Tuple[float, float],
                 dark_noise: float,
                 ...
                 **kwargs: t.Any  # Use this if you want to be forgiving when using a config file dict as input.
    ):
        self.pixels = pixels
        self.pixel_size = pixel_size
        self.dark_noise = dark_noise
```

The way to instantiate the above class is as follows,

```
def test_ccd(ccd_test_config: t.Dict[str, t.Any]):
    test_ccd_class = solary.instruments.camera.CCD(**ccd_test_config)
```

There is another alternative and that is to use the new Python 3.7 `dataclass` or the `attrs` package.
For more information refer to: [Dataclasses and attrs: when and why](https://www.revsys.com/tidbits/dataclasses-and-attrs-when-and-why/)

**Comment by ThomasAlbin** [comment]
I linked this issue with a recent PR. Future classes will consider the dataclasses decorator and any present classes that need major revision will be edited accordingly.
