### ISSUE TITLE
Include versioneer to handle automatic version numbering.

### ISSUE THREAD

**Issue by Hans-Smit** [ThomasAlbin/SolarY#8]
This will ensure that the version numbers are correct and according to `pip` standards. 

This will impact your `solary.__init__.py` file as follows:

```
import os
ROOT_DIR = os.path.dirname(os.path.abspath(__file__))

__project__ = "SolarY"
__author__ = "Dr.-Ing. Thomas Albin"
__email__ = "<add your email>
# __version__ = "deploy"  # COMMENTED THE OLD VERSION

# NEW CODE STARTS HERE
from ._version import get_versions
__version__ = get_versions()['version']
__date__ = get_versions()['date']
del get_versions
# END OF NEW CODE

from . import _config

from . import tests

from . import auxiliary
from . import general
from . import asteroid
from . import neo

from . import instruments
```

The generic `_version.py` script will need to be added along side the `__init__.py` file, and the `versioneer.py` in the `SolarY` project root directory.

For more details:

[versioneer](https://github.com/python-versioneer/python-versioneer)

**Comment by Hans-Smit** [comment]
I've just now included versioneer in my local branch. Here's how it works,

```
% git tag 0.5.7
python       
>>> import SolarY
>>> SolarY.__version__
'0.5.7+0.g2edda58.dirty'
>>> 
```

The ``g2edda58.dirty`` means there are uncommitted changes based on commit hash ``g2edda58``. The ``+0`` means there are 0 commits in the ``0.5.7`` tagged version.

```
% git commit -m "+ADD: added support for versioneer"
% git push
% git tag 0.5.9
% python
>>> import SolarY
>>> SolarY.__version__
'0.5.9'
```

This is my local (pristine) version.

**Comment by ThomasAlbin** [comment]
Thanks to your PR this issue is now resolved
